anchor_version = "0.22.1"
solana_version = "1.9.12"

[features]
seeds = true

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "./test_wallet.json"

[scripts]
test = "yarn mocha"

[programs.localnet]
cpamm = "SCHAtsf8mbjyjiv4LkhLKutTf6JnZAbdJKFkXQNMFHZ"

[programs.testnet]
cpamm = "SCHAtsf8mbjyjiv4LkhLKutTf6JnZAbdJKFkXQNMFHZ"

[programs.devnet]
cpamm = "SCHAtsf8mbjyjiv4LkhLKutTf6JnZAbdJKFkXQNMFHZ"

[programs.mainnet]
cpamm = "SCHAtsf8mbjyjiv4LkhLKutTf6JnZAbdJKFkXQNMFHZ"
