anchor_version = "0.19.0"
solana_version = "1.8.9"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "./test_wallet.json"

[scripts]
test = "yarn mocha"

[programs.localnet]
cpamm = "SCHAtsf8mbjyjiv4LkhLKutTf6JnZAbdJKFkXQNMFHZ"

[programs.testnet]
cpamm = "SCHAtsf8mbjyjiv4LkhLKutTf6JnZAbdJKFkXQNMFHZ"

[programs.devnet]
cpamm = "SCHAtsf8mbjyjiv4LkhLKutTf6JnZAbdJKFkXQNMFHZ"

[programs.mainnet]
cpamm = "SCHAtsf8mbjyjiv4LkhLKutTf6JnZAbdJKFkXQNMFHZ"
